version: "3.7"
services:
  backend:
    build: ./backend
    command: ["sh", "/app/backend/scripts/run-prod.sh"]
    volumes:
      - backend_data:/root/uploads
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      DATABASE_URL: "mysql+pymysql://audino:audino@mysql/audino?charset=utf8mb4"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_REDIS_STORE_URL: "redis://:audino@redis:6379/0"
    depends_on:
      - mysql
      - redis
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./frontend
    volumes:
      - www:/app/frontend/build

  nginx:
    build: ./nginx
    volumes:
      - www:/var/www/html:ro
      - ./nginx/nginx_local.conf:/etc/nginx/nginx.conf:ro
    #  - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
    networks:
      - frontend-network

  mysql:
    build: ./mysql
    volumes:
      - ./mysql:/mysql
      - mysql_prod_data:/var/lib/mysql
    #  - ./rclone/data:/mnt/backup:shared
    environment:
      MYSQL_DATABASE: "audino"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "audino"
      MYSQL_PASSWORD: "audino"
    #depends_on:
    #  - rclone
    networks:
      - backend-network
    command: --user=root --init-file=/mysql/create_database.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  redis:
    build: ./redis
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "audino"
    networks:
      - backend-network
      
  #rclone:
  #  image: rclone/rclone:latest
  #  volumes:
  #    - './rclone/config:/config/rclone'
  #    - './rclone/data:/mnt/data:shared'
  #    - '/etc/passwd:/etc/passwd:ro'
  #    - '/etc/group:/etc/group:ro'
  #  cap_add:
  #    - MKNOD
  #    - SYS_ADMIN
  #  security_opt:
  #    - apparmor:unconfined
  #  privileged: true
  #  devices:
  #    - /dev/fuse
  #  command: 'mount --allow-non-empty e4e:Backup /mnt/data --vfs-cache-mode writes'

volumes:
  mysql_prod_data:
  redis_data:
  backend_data:
  www:

networks:
  backend-network:
  frontend-network:
